// Generated by https://quicktype.io
// https://data.covid19.go.id/public/api/update.json

export interface CovidID {
  data: Data;
  update: UpdateClass;
}

export interface Data {
  id: number;
  jumlah_odp: number;
  jumlah_pdp: number;
  total_spesimen: number;
  total_spesimen_negatif: number;
}

export interface UpdateClass {
  penambahan: Penambahan;
  harian: Harian[];
  total: Total;
}

export interface Harian {
  key_as_string: Date;
  key: number;
  doc_count: number;
  jumlah_meninggal: Jumlah;
  jumlah_sembuh: Jumlah;
  jumlah_positif: Jumlah;
  jumlah_dirawat: Jumlah;
  jumlah_positif_kum: Jumlah;
  jumlah_sembuh_kum: Jumlah;
  jumlah_meninggal_kum: Jumlah;
  jumlah_dirawat_kum: Jumlah;
}

export interface Jumlah {
  value: number;
}

export interface Penambahan {
  jumlah_positif: number;
  jumlah_meninggal: number;
  jumlah_sembuh: number;
  jumlah_dirawat: number;
  tanggal: string;
  created: string;
}

export interface Total {
  jumlah_positif: number;
  jumlah_dirawat: number;
  jumlah_sembuh: number;
  jumlah_meninggal: number;
}
